---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend-dev
spec:
  routes:
    - kind: Rule
      match: 'PathPrefix(`/backend`) && Headers(`Ring`, `dev`)'
      middlewares:
        - name: backend-dev
      services:
        - name: backend-dev
          port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: backend-dev
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /backend

