---

apiVersion: v1
kind: Service
metadata:
  name: frontend-securitybugfix
spec:
  selector:
    app: frontend-securitybugfix
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-securitybugfix
spec:
  selector:
    matchLabels:
      app: frontend-securitybugfix
      tier: frontend
      track: stable
  replicas:  
  template:
    metadata:
      labels:
        app: frontend-securitybugfix
        tier: frontend
        track: stable
    spec:
      containers:
      - name: frontend-securitybugfix
        image: samiyaakhtar/helloworldfullstack:client
        imagePullPolicy: IfNotPresent
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: REACT_APP_BACKEND_URL
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]


